language: r
sudo: required
warnings_are_errors: true

r_binary_packages:
  - data.table
  - dplyr
  - ggplot2
  - knitr
  - rmarkdown
  - magrittr
  - microbenchmark
  - testthat

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
